# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B -DskipTests clean package --file pom.xml
    
    - name: Maven Test
      run: mvn test

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s C:/Users/dines/actions-runner/actions-runner-win-x64-2.294.0/PineLabs/java-practice/java-practice/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
